# 应用名称
spring:
  application:
    name: springcloud-demo-trubine

server:
  port: 8085
  servlet:
    context-path: /mvc3-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/



management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"

turbine:
  app-config: springcloud-demo-mvcservice,springcloud-demo-eurekaclient1
  aggregator:
    clusterConfig: default
  clusterNameExpression: new String("default")
  combine-host: true
  instanceUrlSuffix:
    default: actuator/hystrix.stream