spring:
  datasource:
    name: study
    url: jdbc:mysql://localhost:3306/study2?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&autoReconnectForPools=true&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    username: root
    password: 516516
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: springcloud-demo-eurekaclient1

  resources:
    static-locations: classpath:/static/

  thymeleaf:
    prefix:
      classpath: prefix:classpath:/templates/
    cache: false
    suffix: .html
    encoding: UTF-8

server:
  port: 8081
  servlet:
    context-path: /mvc2-service

mybatis:
  mapper-locations: classpath:com/springcloud/personal/system/springclouddemoeurekaclient1/mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/